### ISSUE TITLE
BDStillImageCamera asks for Microphone permission

### ISSUE THREAD

**Issue by brandons** [Borodutch/BDCamera#5]
BDCamera creates a capture session that includes non optional audio input. Our app only needs to take photos, however since an audio input is added users are asked for Microphone permission.

**Comment by leoru** [comment]
Microphone permission needed because BDStillImageCamera based on AVFoundation and video output.

**Comment by brandons** [comment]
Nope. You can disable microphone input while still having video input. In my fork I just disabled the microphone everywhere, since I'm never recording video. However, it would be possible to disable audio just for the still image camera. 

My fork is working for still image capture without asking for microphone permission.

https://github.com/brandons/BDCamera/commit/992f26316677fc40e32d0a31a3d15917d52d9758

**Comment by leoru** [comment]
Okay, i'm sorry. Maybe you can send me a pull request with this fix?
